export const ADD_VIDEOFILE = "ADD_VIDEOFILE";
export const ADD_VIDEOPLAYER = "ADD_VIDEOPLAYER";
export const VIDEO_SLIDER_VALUE = "VIDEO_SLIDER_VALUE";
export const VIDEO_BRIGHT_VALUE = "VIDEO_BRIGHT_VALUE";
export const VIDEO_FADE_IN_OUT_VALUE = "VIDEO_FADE_IN_OUT_VALUE";
